### ISSUE TITLE
date range functionality idea

### ISSUE THREAD

**Issue by Sheshydev** [asmpro7/DdFlow#1]
Hi there,

I had an idea for this plugin: what if we added a function that allows the user to check how many days/weeks/years are in a date range?

The idea stemmed from when I was filling in paperwork (e.g., how many months did you work here for?) and I needed a quick way to calculate that.

The plugin could also be a more general date plugin instead of just fetching the day of the week (e.g. more functionality such as converting Unix time to days).

I would also be happy to contribute to the code.

Kind regards,
Sheshydev

**Comment by asmpro7** [comment]
Hi Sheshydev,

That sounds like a great idea for a plugin! Adding a function that allows users to calculate the duration in days, weeks, or years for a given date range would definitely be useful in various scenarios.

Expanding the plugin to include more date-related functionality, such as converting Unix time to days, would make it even more versatile and valuable.
and we can add timezones function also. 

If you're interested in contributing to the code, that would be fantastic! Open-source projects often thrive on collaboration, and your contributions would be highly appreciated.

Kind regards,
Ahmed ElSaeed

**Comment by Sheshydev** [comment]
Hi Ahmed,

Thanks for responding to my issue and making it welcoming for me as a new contributor! 

The consideration of timezones would be interesting as well! I'll fork the project and start working on expanding the project's functionalities.

Kind regards,
Thomas (Sheshydev)
